[module.hue]
content = ""
style.foreground = "${~colors.yellow}"
style.background = "${~colors.background-alt}"

enable-scene = "${~dirs.scripts}/hue/enable-scene.sh"
on.click-left = '${enable-scene} "Night Time"'
on.click-middle = '${enable-scene} "Main"'
on.click-right = '${enable-scene} "Morning"'
