[module.notifications]
content = { "false": "", "true": "" }
content.switch = "exec dunstctl is-paused"
style.foreground = "${~colors.red}"
style.background = "${~colors.background-alt}"

on.click-left = "dunstctl set-paused toggle"
update.on.click-left = true
update.interval = 1
