# TODO: How to handle tail...
# TODO: Supporting long running processes invoked by the modules?
# And allowing those processes to be started for each bar or a single instance for all bars
[module.pomodoro]
# MAKE SURE TO RUN ~/scripts/polybar/polypomo/polypomo > /tmp/polypomo.status somewhere.
# I put this in my bspwmrc which also starts polybar
exec = "tail -f -n 1 /tmp/polypomo.status"
tail = true

style.foreground = "${~colors.lavendar}"
style.background = "${~colors.background-alt}"
on.click-left = "${~dirs.scripts}/polypomo.py toggle"
on.click-right = "${~dirs.scripts}/polypomo.py end"
on.click-middle = "${~dirs.scripts}/polypomo.py lock"
