# TODO: How to handle tail...
[module.song-recognition]
type = "custom/script"

exec = "~/scripts/polybar/songrec/stop.sh /tmp/songrec.status && tail -f -n 1 /tmp/songrec.status"
tail = true

on.click-left = "~/scripts/polybar/songrec/start.sh /tmp/songrec.status"
on.click-right = "~/scripts/polybar/songrec/stop.sh /tmp/songrec.status"

format-foreground = "${colors.teal}"
format-background = "${colors.background-alt}"
