[module.update-wallpaper]
content = "юди"
style.font = "${~fonts.icons}"
style.foreground = "${~colors.blue}"
style.background = "${~colors.background-alt}"
on.click-left = "${~dirs.scripts}/wallpaper/set-wallpaper.sh $(${~dirs.scripts}/wallpaper/get-wallpaper.sh)"
